[package]
name = "yake"
version = "0.1.0"
edition = "2021"

[dependencies]
yake-rust = { path = "../yake_rust" , features = ["serde"]}
clap = { version = "4.5.26", features = ["cargo", "derive", "string"] }
serde_json = "1.0.135"
exit-code = "1.0.0"
